version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST={DB_HOST}
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - DB_NAME={DB_NAME}
      - DB_PORT={DB_PORT}
    depends_on:
      - db

